FROM repo-img.infocms.com.vn/infocms/builder/nodejs-web-yarn:latest AS node_base
# ------------------------------------------------------
# Production Build docker pull node:16.14.0-alpine
# ------------------------------------------------------
WORKDIR /usr/src
#RUN echo "NODE Version:" && node --version
#RUN echo "NPM Version:" && npm --version


RUN rm -rf $(ls -A | grep -v node_modules)
COPY package-lock.json .
COPY package.json .

RUN npm install
ENV TZ=Asia/Ho_Chi_Minh
#RUN npm i -g rimraf
# Build project
COPY . /usr/src

RUN ls /usr/src

RUN npm run build

RUN ls /usr/src

# ------------------------------------------------------
# Production Deploy
# ------------------------------------------------------
FROM repo-img.infocms.com.vn/infocms/builder/reactjs-web-nginx118:20231016
COPY --from=node_base /usr/src/dist/ /usr/share/nginx/html
COPY --from=node_base /usr/src/src/config/admin_cms_uat.conf /etc/nginx/conf.d/default.conf

